version: "3.8"
services:
  db:
    image: postgres:15
    container_name: psqldb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./docker-data/psql:/var/lib/postgresql/data
  pgadmin:
    user: root
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@psql.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./docker-data/pgadmin:/var/lib/pgadmin